env:
  browser: true
  es2021: true
extends:
  - react-app
  - react-app/jest
  - plugin:react/recommended
  - airbnb
  - airbnb-typescript
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - "@typescript-eslint"
  - testing-library
rules:
  react/react-in-jsx-scope: off
  import/prefer-default-export: off
  react/button-has-type: off
  arrow-body-style: off
  react/require-default-props: off
  react/jsx-props-no-spreading: off
  "@typescript-eslint/no-unused-vars": off
  testing-library/no-render-in-setup:
    - error
    - allowTestingFrameworkSetupHook: beforeEach
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
  "@typescript-eslint/no-shadow": off
