version: "3"

services:
  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./client:/client
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - 8000:8000
    tty: true
    volumes:
      - ./server:/server
  db:
    image: postgres:11
    ports:
      - 54432:5432
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: password
#    volumes:
#      - ./db/data:/var/lib/postgresql/data