version: "3"

services:
  client:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    command: sh -c "npm run dev"
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./client:/client
    depends_on:
      - db
      - server
  server:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/server
    depends_on:
      - db
  db:
    image: postgres:11
    ports:
      - 54432:5432
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: password
#    volumes:
#      - ./db/data:/var/lib/postgresql/data