version: "3"

services:
  client:
    build:
      context: .
      dockerfile: docker/react/Dockerfile
    command: sh -c "npm rebuild esbuild && npm start"
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./client:/client
    depends_on:
      - db
      - server
  server:
    build:
      context: .
      dockerfile: docker/go/Dockerfile
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./server:/server
    depends_on:
      - db
  db:
    image: postgres:11
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: attendance_management_development,attendance_management_test
    ports:
      - 5432:5432
